// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmQn7nyTIiFyeUCqNZjhIOBC2wk5FqHc8',
    appId: '1:951703786122:web:9c71f65d90efc511a91373',
    messagingSenderId: '951703786122',
    projectId: 'fir-13e5a',
    authDomain: 'fir-13e5a.firebaseapp.com',
    storageBucket: 'fir-13e5a.appspot.com',
    measurementId: 'G-0545Y5EVRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkzhggeIAaVm9XZM9GssHD0Z2R0YyfpT4',
    appId: '1:951703786122:android:0d589989a474c189a91373',
    messagingSenderId: '951703786122',
    projectId: 'fir-13e5a',
    storageBucket: 'fir-13e5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVu9v8cH9uVyqmF8nG9MCEMvGvS8dyn6A',
    appId: '1:951703786122:ios:514c1935010593dea91373',
    messagingSenderId: '951703786122',
    projectId: 'fir-13e5a',
    storageBucket: 'fir-13e5a.appspot.com',
    iosBundleId: 'com.example.bdesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVu9v8cH9uVyqmF8nG9MCEMvGvS8dyn6A',
    appId: '1:951703786122:ios:42a32498a2fad374a91373',
    messagingSenderId: '951703786122',
    projectId: 'fir-13e5a',
    storageBucket: 'fir-13e5a.appspot.com',
    iosBundleId: 'com.example.bdesktop.RunnerTests',
  );
}
